### ISSUE TITLE
Invalid image buffer

### ISSUE THREAD

**Issue by PaschalCollins** [nystudio107/annotated-webpack-4-config#27]
Below is the error I have been getting from the webpack configuration

Paschal Collins@DESKTOP-H75Q2AJ MINGW64 ~/goProject/myProjects/nextProject (master)
$ npm run build

> nextproject@1.0.0 build C:\Users\Paschal Collins\goProject\myProjects\nextProject
> webpack --config webpack.prod.js --progress --hide-modules

No matching files found.

source: http://example.test/ dest: ./web/dist/criticalcss/index_critical.min.css
10% [1] building 0/0 modules 0 activeError: Invalid image buffer
    at Object.source (C:\Users\Paschal Collins\goProject\myProjects\nextProject\node_modules\favicons\dist\helpers.js:171:35)
    at favicons (C:\Users\Paschal Collins\goProject\myProjects\nextProject\node_modules\favicons\dist\index.js:193:26)
    at Object.module.exports (C:\Users\Paschal Collins\goProject\myProjects\nextProject\node_modules\webapp-webpack-plugin\src\loader.js:23:10)
    at LOADER_EXECUTION (C:\Users\Paschal Collins\goProject\myProjects\nextProject\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (C:\Users\Paschal Collins\goProject\myProjects\nextProject\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
    at iterateNormalLoaders (C:\Users\Paschal Collins\goProject\myProjects\nextProject\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\Paschal Collins\goProject\myProjects\nextProject\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\Paschal Collins\goProject\myProjects\nextProject\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\Paschal Collins\goProject\myProjects\nextProject\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\Paschal Collins\goProject\myProjects\nextProject\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
82% [1] emitting ImageminWebpWebpackPluginimagemin-webp-webpack-plugin: 0 KB saved
82% [1] emitting GenerateSW

**Comment by nternetinspired** [comment]
The Critical CSS task is failing because https://example.test/ is not reachable. 

I believe you just need to update your config to point to a valid domain and you'll be good to go.
